version: '2'
services:
  openai-service:
    container_name: openai-service
    build:
      context: openai
      dockerfile: Dockerfile
    image: openai:latest
    ports:
      - "8081:8081"
    volumes:
      - ./data-storage/:/app/data-storage
    environment:
      - eureka.client.serviceUrl.defaultZone= http://eureka-service:8761/eureka
    networks:
      - spring-cloud-network
    depends_on:
      - discovery-service

  discovery-service:
    container_name: eureka-service
    build:
      context: eureka-discovery
      dockerfile: Dockerfile
    image: eureka:latest
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge